"""create example table

Revision ID: c9899636425d
Revises: c7b9407e0a42
Create Date: 2025-05-22 00:15:22.343330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c9899636425d'
down_revision: Union[str, None] = 'c7b9407e0a42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('example_table', sa.Column('enum_type', postgresql.ENUM('optionOne', 'optionTwo', name='example_enum_type'), nullable=False))
    op.alter_column('example_table', 'secondary_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('example_table', 'attack_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('example_table', sa.Column('attack_type', postgresql.ENUM('optionOne', 'optionTwo', name='example_enum_type'), autoincrement=False, nullable=False))
    op.alter_column('example_table', 'secondary_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('example_table', 'enum_type')
    # ### end Alembic commands ###
